xyapp/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('postapp/', include('postapp.urls')),
    path('json/',include('jsonresponse.urls')),
    path('', TemplateView.as_view(template_name="index.html")),
]

xyapp/postapp/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostCreateView,
    PostDeleteView,
    PostDetailView,
    PostUpdateView
)
from . import views

app_name = 'postapp'
urlpatterns = [
    path('', views.home, name='post-home'),
    path('<int:pk>/detail/', PostDetailView.as_view(), name='post-detail'),
    path('new/', PostCreateView.as_view(), name='post-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView, name='post-delete'),
    path('search/', views.SearchMyPost, name='post-search'),
    path('login/', views.signin),
    path('loginAction/', views.signinAction, name='post-login'),
    path('logoutAction/', views.logoutAction, name='post-logout'),
    path('register/', views.register, name='post-register'),
    path('registerAction/', views.registerAction, name='post-register-action'),
    path('userinfo/', views.get_user_info, name='get-user-info'),
    path('UpdateUserInfo/', views.update_user_info, name='update-user-info'),
    path('UpdateUserInfoView/', views.update_user_info_view, name='update-user-info-view'),
]

xyapp/postapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class MyPost(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=50,default="ALL")
    post_visible = models.CharField(max_length=50,default="NO")
    img_name = models.CharField(max_length=100,default="NULL")
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'../../{self.pk}/detail/'

class UserInfo(models.Model):
    author = models.TextField()
    identity = models.TextField()
    info = models.TextField()
    optical_contact_info = models.TextField()
    avatar = models.TextField(default=0)

    def __str__(self):
        return self.author

class Friend(models.Model):
    name1 = models.TextField()
    name2 = models.TextField()
    def __str__(self):
        return self.name1+"&"+self.name2


class AdvancedPost(MyPost):
    academy = models.TextField()
    institution = models.TextField()
    professor = models.TextField()
    def __str__(self):
        return self.academy

xyapp/postapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import MyPost, UserInfo
from .mysearch import search_strategy
from django.contrib.auth.models import User
# Create your views here.

# define a homepage
def home(request):
    context = {
        'posts':MyPost.objects.all()
    }
    return render(request, 'postapp/home.html', context)

# our post list
class PostListView(ListView):
    model = MyPost
    template_name = 'postapp/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']

class PostDetailView(DetailView):
    model = MyPost
    template_name = 'postapp/post_detail.html'

class PostCreateView(LoginRequiredMixin,CreateView):
    model = MyPost
    fields = ['title', 'content']
    success_url = '../'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = MyPost
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def PostDeleteView(request, pk):
    status = request.COOKIES.get('user')
    post = MyPost.objects.get(pk=pk)
    if(status != post.author.username):
        print("not the author of this post")
        return render(request, 'postapp/home.html')# not the author of this post
    post.delete()
    return home(request)




def signin(request):
    return render(request, 'postapp/login.html')

def signinAction(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        
        # set cookie
        context = {
        'posts':MyPost.objects.all()
        }
        rep=render(request, 'postapp/home.html', context)
        rep.set_cookie("user",username)
        return rep


        return home(request)
    else:
        return render(request, 'postapp/login.html',context={
            'err_message':"密码不正确!"
        })
        return HttpResponse("密码不正确")


def logoutAction(request):
    logout(request)

    # delete cookie
    rep=render(request, "postapp/login.html")
    rep.delete_cookie("user")
    return rep

    return render(request, "postapp/login.html")


def register(request):
    return render(request, "postapp/register.html")


def registerAction(request):
    username = request.POST['username']
    password = request.POST['password']
    email = request.POST['email']
    person = User.objects.filter(username=username)
    if any(person):
        return render(request, "postapp/register.html",context={
            'err_message':"您输入的用户名已存在！"
        })
    if len(username)>0 and len(password)>0 and len(email)>0:
        user = User.objects.create_user(username, email, password)
        user.save()
        #return HttpResponse("注册成功！")
        return home(request)
    return render(request, "postapp/register.html",context={
            'err_message':"信息填写不全，注册失败！"
        })




def SearchMyPost(request):
    obj_titles, obj_pk, obj_set = [], [], []
    for obj in MyPost.objects.all():
        obj_titles.append(obj.title)
        obj_pk.append(obj.pk)
    pk_list = search_strategy(request.POST['search-content'], obj_titles, obj_pk)
    for pk in pk_list:
        obj_set.append(MyPost.objects.get(pk=pk))

    context = {
        'posts':obj_set
    }
    return render(request, 'postapp/home.html', context)


def update_user_info_view(request):
    username = request.COOKIES.get("user")
    return render(request, "postapp/update_userinfo.html",{'author': username})


def update_user_info(request):
    username = request.COOKIES.get("user")
    userinfo = UserInfo.objects.filter(author=username)
    if len(userinfo) == 0:
        userinfo = UserInfo(author=username)
    else:
        userinfo = userinfo[0]
    userinfo.identity = request.POST["identity"]
    userinfo.info = request.POST["info"]
    userinfo.optical_contact_info = request.POST["optical_contact_info"]
    userinfo.save()
    context = {
        'author': userinfo.author,
        'identity': userinfo.identity,
        'info': userinfo.info,
        'optical_contact_info': userinfo.optical_contact_info
    }
    return render(request, 'postapp/userinfo.html', context)


def get_user_info(request):
    username = request.COOKIES.get("user")
    userinfo = UserInfo.objects.filter(author=username)
    if len(userinfo) > 0:
        userinfo = userinfo[0]
        context = {
            'author': userinfo.author,
            'identity': userinfo.identity,
            'info': userinfo.info,
            'optical_contact_info': userinfo.optical_contact_info
        }
    else:
        context = {
            'author': username,
            'identity': 'to be filled in',
            'info': 'to be filled in',
            'optical_contact_info': 'to be filled in'
        }
    return render(request, 'postapp/userinfo.html', context)

xyapp/postapp/templates/postapp/home.html
<head>
<title>fieldset Tag</title>
<style>
	p{
	   color:#db7093;
	   margin-left:440px;
	   font-size:40px;
	   font-weight:bold;
		}
	form{
             color:#db7093;
	width:600px;
             height:300px;
	margin:auto;
	margin-top:30px;}
	div{
                 color:white;
	background-color:#db7093;
		}
                  .tx{
	margin-left:20px;
		}
</style>
</head>


<form action="{% url 'postapp:post-search' %}" method="post" class="wd">
{% csrf_token %}
<fieldset class="wd" style="border-width: 2px; border-color: #db7093">
<legend><h1>欢迎使用校易app!</h1></legend>
    <input placeholder="请输入搜索内容" type="text" name="search-content" />
    <input type="submit" value="搜索" name="search">
</fieldset>
{% if user.is_authenticated %}
    <a>欢迎，{{ user.username }}</a><br>
    <a href="{% url 'postapp:post-logout' %}">退出当前账户</a>
    <a href="{% url 'postapp:post-create' %}">发帖</a>
    <a href="{% url 'postapp:get-user-info' %}">账户信息</a>
{% else %}
    <a href="{% url 'postapp:post-logout' %}">登录</a>
{% endif %}
</form>

<fieldset class="wd" style="border-width: 2px; border-color: #db7093">
<legend><h1><font color=" #db7093">搜索结果</font></h1></legend>
{% block content %}
    {% for post in posts %}
        <fieldset class="wd" style="border-width: 2px; border-color: #db7093">
        <article>
        <h2><a href="{% url 'postapp:post-detail' post.id %}"><font color=" #db7093">{{ post.title }}</font></a></h2>
        <div>       
        <label>作者：</label><a>{{ post.author }}</a><br>
        <small><label>发表时间：</label>{{ post.date_posted|date:"F d, Y" }}</small><br>
        <a>内容：{{ post.content }}</a>
        </div>
        </article>
        </fieldset>
    {% endfor %}
{% endblock content %}
</fieldset>

xyapp/postapp/templates/postapp/login.html
<head>
<link rel="stylesheet" type="text/css" href="../../static/css/border01.css">
</head>

<div class="gradient-border" id="box">
<form action="{% url 'postapp:post-login' %}" method="post">
{% csrf_token %}
    <small><small><p>校易APP用户登录界面</p></small></small>
    <small><small><small><label>用户名</label></small></small></small>
    <input placeholder="请输入用户名" type="text" name="username" /><br>
    <small><small><small><label>密码</label></small></small></small>
    <input placeholder="请输入密码" type="password" name="password" /><br>
    {% if err_message %}
    <small><small><small>{{err_message}}</small></small></small>
    {% endif %}

<big><big><input type="submit" value="登录" name="login"></big></big>
<small><small><small><small><small><a href="{% url 'postapp:post-register' %}"><font color="white">注册新用户?</font></a></small></small></small></small></small>
</form>
</div>

xyapp/postapp/templates/postapp/mypost_form.html
{% load crispy_forms_tags %}
{% block content %}

<head>
<title>fieldset Tag</title>
<style>
	p{
	   color:#db7093;
	   margin-left:440px;
	   font-size:40px;
	   font-weight:bold;
		}
	form{
             color:white;
	width:600px;
             height:300px;
	margin:auto;
	margin-top:30px;}
	div{
	background-color:#28455e;
		}
                  .tx{
	margin-left:20px;
		}
</style>
</head>

<div>
<form method="post" class="wd">
{% csrf_token %}
<fieldset class="wd">
<legend>校易发帖</legend>
{{ form|crispy }}
</fieldset>
<div>
<button type="submit">发布</button>
</div>
</form>
</div>
{% endblock content %}

xyapp/postapp/templates/postapp/post_detail.html
<head>
<link rel="stylesheet" type="text/css" href="../../../static/css/border02.css">
</head>


<div class="container-block">
	<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/65984/photo-1413752567787-baa02dde3c65.jpg">
	<div class="inner-block">
		<div class="slider-top-right"></div>
	</div>
	<div class="block-content">
{% block content %}
<article>

<h2>{{ object.title }}</h2>
<label>作者：</label><a>{{ object.author }}</a><br>
<small><label>发表时间：</label>{{ object.date_posted|date:"F d, Y" }}</small>
<p>{{ object.content }}</p>

{% if object.author == user %}
<a href="{% url 'postapp:post-update' object.id %}"><font color="white">更新</font></a>
<a href="{% url 'postapp:post-delete' object.id %}"><font color="white">删除</font></a>
{% endif %}
<a href="{% url 'postapp:post-home' %}"><font color="white">返回主页</font></a>
</article>
{% endblock content %}
	</div>
</div>

xyapp/postapp/templates/postapp/register.html
<head>
<link rel="stylesheet" type="text/css" href="../../static/css/border01.css">
</head>

<div class="gradient-border" id="box">
<form action="{% url 'postapp:post-register-action' %}" method="post">
{% csrf_token %}
    <small><small><small><p>校易APP新用户注册界面</p></small></small></small>
    <small><small><small><small><label>用户名</label></small></small></small></small>
    <input placeholder="请输入用户名" type="text" name="username" /><br>
    <small><small><small><small><label>密码</label></small></small></small></small>
    <input placeholder="请输入密码" type="password" name="password" /><br>
    <small><small><small><small><label>邮箱</label></small></small></small></small>
    <input placeholder="请输入邮箱" type="email" name="email" /><br>

    {% if err_message %}
    <small><small><small>{{err_message}}</small></small></small>
    {% endif %}
    <big><big><input type="submit" value="注册"></big></big>
</form>
</div>

xyapp/postapp/templates/postapp/update_userinfo.html
<form action="{% url 'postapp:update-user-info' %}" method="post">
{% csrf_token %}
<fieldset>
<label>用户名：</label><a>{{ author }}</a><br>
<label>身份：</label><input placeholder="请输入新的身份" type="text" name="identity" /><br>
<label>信息：</label><input placeholder="请输入新的信息" type="text" name="info" /><br>
<label>可选联系信息：</label><input placeholder="请输入新的联系信息" type="text" name="optical_contact_info" /><br>
</fieldset>
<input type="submit" value="提交">
</form>

xyapp/postapp/templates/postapp/userinfo.html
<fieldset>

<label>用户名：</label><a>{{ author }}</a><br>
<label>身份：</label><a>{{ identity }}</a><br>
<label>信息：</label><a>{{ info }}</a><br>
<label>可选联系信息：</label><a>{{ optical_contact_info }}</a><br>
</fieldset>
<a href="{% url 'postapp:update-user-info-view' %}"><font color="pink">更新信息</font></a>
<a href="{% url 'postapp:post-home' %}"><font color="pink">返回主页</font></a>